### ISSUE TITLE
Sprint1 team collobaration

### ISSUE THREAD

**Issue by kajayr** [kajayr/CAPSTONE#1]
- [x] All members shared the contact Information
- [x] All members have created the GitHub Account
- [ ] All members have a complete understanding about the project
- [x] Sending invitation on GitHub for Maricel
- [ ] The product manager has research the required websites related to the project
- [ ] List of tasks and member in charge for the next two weeks based on the requirements
- [ ] Next meeting on Tuesday 1/30/2018

Will add more tasks for the next week soon

**Comment by maricel0422** [comment]
Excellent.... Just make sure that we add specificity and outcomes to the tasks.  You can also add tasks to me!
