### ISSUE TITLE
Review wiki page about Use Case

### ISSUE THREAD

**Issue by maricel0422** [kajayr/CAPSTONE#7]
I just posted a clear example of what we need as instructors.  Currently, a faculty sends an email to a group of faculty.  The message may reach the students only if the faculty share the message.  We want to change that. We want to democratize the opportunities and make the process available to all.

Please take a look and review this case. How would our application handle this information?

**Comment by kajayr** [comment]
This was an amazing reminder that you wrote it down here Miracel. Thank you. We have a special Skype meeting tonight to make sure that all members of the team will have a clear understanding of the project. For sure I will encourage them to visit the wiki page about Use Case. Thanks a lot

**Comment by maricel0422** [comment]
Please, let me know if you need anything else... I still can draw a diagram and I have a clear understanding of my expectations but I want to make sure you are able to capture my needs and ask me questions.

Basically, we have three users:

- Faculty:  The post "jobs/tasks" including, dates/times, number of hours, place, description.  The tasks can be recurrent and it can include a number of individuals (considered the option of signing up and fill slots).  A faculty can assign the task to a class (consider the need of integrating with HR/classes system) and of course to a quarter.  But only to classes what the instructor is teaching.  IDEAL:  This can be integrated potentially with Canvas as an assignment. The CANVAS API could do this although this is out of scope for this quarter

- Staff:  Staff can post tasks (similar to the one Sapan posted today).  They are not necessarily related to a class but a faculty can "copy the task" and assign it to a class and give extra credit

NOTE:  Consider providing a way to open tasks only for students or the community in general.

- Students can sign up to the tasks, make comments, send messages to the staff/faculty. Students should be able to withdraw themselves from a task.

In general, an admin process should allow faculty/staff to delete/update/add tasks.

For all the account on the system (faculty, staff, students), eventually, we may be able to integrate with Canvas and get the minimum information (profile picture, name and ID).

The system should provide a way to get notifications by SMS, or email.

It would be nice to give badges to students who are participating in the tasks.

**Comment by maricel0422** [comment]
I will close this tasks and just copied my requirements to to a new [Wiki Page](https://github.com/kajayr/CAPSTONE/wiki/Basic-Requirements)
